### ISSUE TITLE
How can I update to the latest taunts?

### ISSUE THREAD

**Issue by DennisL94** [fakuivan/TF2-Taunts-TF2IDB#34]
I know the Heavy has more taunts than what's currently shown**, so how can I get my tf2itemsdb to actually give me all up to date.**

I'm sure it'll help others as well. I'm new to this so please pardon me!

**Comment by fakuivan** [comment]
For issues with tf2idb itself please report them to the tf2idb repo, there's currently no mechanism implemented to pull taunt data from other than the supported APIs.

https://github.com/flaminsarge/tf2idb/issues
