### ISSUE TITLE
The plug-in isn't working.

### ISSUE THREAD

**Issue by Dmitry9000YT** [fakuivan/TF2-Taunts-TF2IDB#39]
I made a post about it on reddit.
https://www.reddit.com/r/tf2/comments/lwirbm/tf2_items_info_doesnt_work/
But in short, Whenever I try to load up my server I get this:
L 03/03/2021 - 09:54:18: [SM] [2] Line 1562, tf2itemsinfo.sp::PrecacheItemSchema

L 03/03/2021 - 09:54:18: [SM] [3] Line 269, tf2itemsinfo.sp::OnPluginStart

L 03/03/2021 - 09:54:18: [SM] Unable to load plugin "tf2itemsinfo.smx": Error detected in plugin startup (see error logs)

**Comment by fakuivan** [comment]
@Dmitry9000YT, this doesn't seem to be an issue regarding this plugin. refer to the tf2itemsinfo repository for any issues related to that.
