### ISSUE TITLE
Not all taunts show up in the taunt menu

### ISSUE THREAD

**Issue by gamermonter** [fakuivan/TF2-Taunts-TF2IDB#41]
what do I do?

**Comment by fakuivan** [comment]
Start by describing your problem, only then I'll be able to help you. "Issues" here concern issues with the code or the documentation, for general help use the AM forums.

**Comment by gamermonter** [comment]
when I write in the chat !taunt does not appear all taunt only a few, for example the spy doesn’t have the one he dances to

**Comment by gamermonter** [comment]
(im use to google translate)

**Comment by fakuivan** [comment]
I'm guessing you're using tf2idb, in that case make sure the item database is up to date. Refer to https://github.com/FlaminSarge/tf2idb or the link in the [readme](README.md) for how to do that.

**Comment by gamermonter** [comment]
ready I downloaded, now it will work ?.
And yes I do, in the addons / soucemod folder.

**Comment by gamermonter** [comment]
in my server

**Comment by gamermonter** [comment]
ha and on this site, I didn't find where to say to update the database

**Comment by fakuivan** [comment]
I didn't give the steps to install it either, the link to the forum post for the plugin should have all the info you need. Once you updated the database and confirmed everything works as expected, close this issue.

**Comment by gamermonter** [comment]
I downloaded it, but still it doesn't have all the taunts

**Comment by fakuivan** [comment]
Update the database. Use the python script provided with the tf2idb plugin, ask on the forum or open an issue in the repo if you need more assistance.

**Comment by gamermonter** [comment]
ok, how do they appear and also I try to use python and I can't, and you can't leave it configured because I can't configure

**Comment by gamermonter** [comment]
Oops, sorry I was very young at the time and didn't know what I was doing, but today I saw it and updated it, but it still doesn't show all the teasing, please help me with this
