### ISSUE TITLE
Update the plugin to Winter 2021/Summer 2022 or allow the plugin to detect new added taunts.

### ISSUE THREAD

**Issue by sniperstyx** [fakuivan/TF2-Taunts-TF2IDB#43]
Essentially an update that allows the plugin to scan for any new taunts that have been added during summer, winter or halloween events.

If that's not possible, then add the latest taunts that have been added before or after Summer 2022.

**Comment by fakuivan** [comment]
This plugin is not in charge of reading item info, it merely asks for all taunt ids to item schemas, if you need the latest taunts then ensure that your item schema plugin is delivering updated information. Unless the way taunts are stored into the schema changed, this plugin does not need to be updated (as it has been the case for years lol).

**Comment by sniperstyx** [comment]
Well if that won't be possible, then there should be an update to tf2idb.sq3. If there is one already, can someone link it here?

**Comment by fakuivan** [comment]
I don't have an updated version of the database available right now. You can ask for one on the tf2idb forum thread. Issues in this repo should be specific to this plugin, this is a tf2idb issue.
