### ISSUE TITLE
Plugin fails to load properly, suggests installing latest version

### ISSUE THREAD

**Issue by TinyDeskEngineer06** [fakuivan/TF2-Taunts-TF2IDB#44]
I've installed this plugin on a dedicated server, but every time I try to load it, it says `L 04/10/2023 - 14:00:52: [tf2_taunts_tf2idb.smx] Failed to initialize taunt cache: TF2IDB Not loaded.
L 04/10/2023 - 14:00:52: [tf2_taunts_tf2idb.smx] Halting user interface initialization. Plugin loaded but updater not found.
L 04/10/2023 - 14:00:52: [tf2_taunts_tf2idb.smx] Try using the latest version from here https://github.com/fakuivan/TF2-Taunts-TF2IDB .`
SourceMod says the plugin loaded successfully, but it doesn't seem to work. sm_taunt_list results in getting an "Unknown command" error. I am also entirely sure I have installed the latest version of the plugin from this repository.

**Comment by fakuivan** [comment]
As it's noted in the error log: ``TF2IDB Not loaded``, means you need to install TF2IDB or any of the compatibility layers like https://github.com/nosoop/SM-TFEconDataCompat

**Comment by TinyDeskEngineer06** [comment]
> As it's noted in the error log: `TF2IDB Not loaded`, means you need to install TF2IDB or any of the compatibility layers like https://github.com/nosoop/SM-TFEconDataCompat

Right, I probably should've mentioned this, I don't know why I didn't, but I've also already installed TF2IDB on the server too, and it's not giving me an error either.

**Comment by madiskoivopuu** [comment]
The related error is coming from the taunt cache system.
```sourcepawn
if (!LibraryExists("tf2idb"))
{
	i_error = CTauntCacheSystem_FromTF2IDB_Error_TF2IDBNotLoaded;
	return INVALID_TAUNT_CACHE_SYS;
}

```
What LibraryExists does is check if the plugin (in this case TF2IDB) has registered itself as a library using some sort of function. Since it’s failing and you did mention that there’s no errors being given by TF2IDB, then it could be that the plugin is not loading at all or there’s some silent error which doesn’t get logged. Try checking the plugins list to see if it’s loaded & running.
If it’s the case that there is a silent error, it could help to just install the entire plugin along with its sqlite database from scratch

**Comment by fakuivan** [comment]
> Right, I probably should've mentioned this, I don't know why I didn't, but I've also already installed TF2IDB on the server too, and it's not giving me an error either.

Having it installed is not the same as it loading properly. Check if TF2IDB failed to load, there's probably an issue with the database as @madiskoivopuu mentioned. Use [SM-TFEconDataCompat](https://github.com/nosoop/SM-TFEconDataCompat) instead, you don't need to update any databases.

**Comment by fakuivan** [comment]
Closing this as it seems to be the usual TF2IDB issue https://github.com/FlaminSarge/tf2idb/issues/35

**Comment by TinyDeskEngineer06** [comment]
Still not working after switching to TFEconData, and this time there aren't any errors from or referring to other plugins. Also tried reloading this plugin, but nothing happened. The error log says "Failed to initialize taunt cache, error code 1"
