### ISSUE TITLE
TFEconData with tf2idb adapter: failed to initialize cache with error 1

### ISSUE THREAD

**Issue by fakuivan** [fakuivan/TF2-Taunts-TF2IDB#45]
Still not working after switching to TFEconData, and this time there aren't any errors from or referring to other plugins. Also tried reloading this plugin, but nothing happened. The error log says "Failed to initialize taunt cache, error code 1"

_Originally posted by @TinyDeskEngineer06 in https://github.com/fakuivan/TF2-Taunts-TF2IDB/issues/44#issuecomment-1509444123_

**Comment by fakuivan** [comment]
That error code seems to be related to finding item ids using sqlite queries. From what I understard TFEconData does emulate the SQLite database used by TF2IDB so in theory there shouldn't be any issues, but just in case, you can try the tf2ii version of this plugin instead. The tf2ii version of this plugin does not access any data internal to tf2ii, so it should have better compatibility. Besides item schema support, the tf2idb and the tf2ii version of this plugin are identical.

The tf2idb error codes:

https://github.com/fakuivan/TF2-Taunts-TF2IDB/blob/00bac1b8aa43e140ba1f12d7756b98df5a7989bd/scripting/include/tf2_taunts_tf2idb/taunt_cache_system.inc#L26-L34

Where code 1 is raised:

https://github.com/fakuivan/TF2-Taunts-TF2IDB/blob/00bac1b8aa43e140ba1f12d7756b98df5a7989bd/scripting/include/tf2_taunts_tf2idb/taunt_cache_system.inc#L87-L94

**Comment by TinyDeskEngineer06** [comment]
It's working now!
