### ISSUE TITLE
Native functions for use in own plugins

### ISSUE THREAD

**Issue by flleeppyy** [fakuivan/TF2-Taunts-TF2IDB#46]
Are there any plans to be able to list and force taunts via an include file/natives so that we can use it in our own plugins? I'm making an RTD plugin and one of the perks is disco ball, which needs to force taunts on players, and this plugin is the only one I see fit.

**Comment by fakuivan** [comment]
There are no natives for communication between plugins iirc, however this file has all the implementation details for the forcing taunts bits, you might want to take a look and see how it's being used.
https://github.com/fakuivan/TF2-Taunts-TF2IDB/blob/master/scripting/include/tf2_taunts_tf2idb/taunt_enforcer.inc
